import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// ---------------------------------------------------------------------------
// Docusaurus config — generated by /lore:init.
// The wizard fills every {{PLACEHOLDER}} and writes the i18n block per the
// chosen documentation language:
//   • RTL (e.g. Persian): direction 'rtl', and customCss includes custom-rtl.css
//   • LTR (e.g. English): direction 'ltr', custom-rtl.css omitted
// To add a logo/favicon later: drop files in static/img/ and re-add the
// `favicon`, `navbar.logo`, and `themeConfig.image` fields (see SETUP.md).
// ---------------------------------------------------------------------------

const config: Config = {
  title: '{{SITE_TITLE}}',
  tagline: '{{SITE_TAGLINE}}',

  url: 'https://{{PROJECT_SLUG}}.pages.dev',
  baseUrl: '/',

  organizationName: '{{ORG}}',
  projectName: '{{PROJECT_SLUG}}',

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: '{{LOCALE}}',
    locales: ['{{LOCALE}}'],
    localeConfigs: {
      '{{LOCALE}}': {
        label: '{{LANG_LABEL}}',
        direction: '{{DIRECTION}}',
        htmlLang: '{{HTML_LANG}}',
      },
    },
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          // RTL builds: ['./src/css/custom.css', './src/css/custom-rtl.css']
          // LTR builds: ['./src/css/custom.css']
          customCss: ['./src/css/custom.css'],
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: '{{SITE_TITLE}}',
      items: [],
    },
    footer: {
      style: 'dark',
      links: [],
      copyright: '{{COPYRIGHT}}',
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
