import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// ---------------------------------------------------------------------------
// Docusaurus config — generated by /lore:init.
// The wizard fills every {{PLACEHOLDER}} and writes the i18n block per the
// chosen documentation language:
//   • RTL (e.g. Persian): direction 'rtl', and customCss includes custom-rtl.css
//   • LTR (e.g. English): direction 'ltr', custom-rtl.css omitted
// To add a logo/favicon later: drop files in static/img/ and re-add the
// `favicon`, `navbar.logo`, and `themeConfig.image` fields.
// ---------------------------------------------------------------------------

const config: Config = {
  title: '{{SITE_TITLE}}',
  tagline: '{{SITE_TAGLINE}}',

  // Production deploy URL — the origin of every absolute link Docusaurus generates:
  // the canonical <link>, the og: tags, and every entry in sitemap.xml. Local dev
  // (`npm start`) ignores it. The wizard fills it; if the site is not deployed yet it
  // writes http://localhost:3000, which is *wrong but obviously wrong*. It used to ship
  // the framework's own `https://your-docusaurus-site.example.com`, which is wrong and
  // looks deliberate — so every generated site published a sitemap pointing at a domain
  // nobody owns. Update it the day you deploy.
  url: '{{SITE_URL}}',
  baseUrl: '/',

  organizationName: '{{ORG}}',
  projectName: '{{PROJECT_SLUG}}',

  // 'throw', not 'warn'. The production build is what the Definition of Done leans on as
  // its authoritative link check (§6), and a warning does not gate anything — the build
  // went green with dead links in it while the docs promised the opposite.
  onBrokenLinks: 'throw',
  // onBrokenMarkdownLinks defaults to 'warn'. Not set explicitly: the top-level
  // option is deprecated in Docusaurus 3.9+ (moved to markdown.hooks) and removed
  // in v4 — omitting it keeps the 'warn' default across every Docusaurus version.

  i18n: {
    defaultLocale: '{{LOCALE}}',
    locales: ['{{LOCALE}}'],
    localeConfigs: {
      '{{LOCALE}}': {
        label: '{{LANG_LABEL}}',
        direction: '{{DIRECTION}}',
        htmlLang: '{{HTML_LANG}}',
      },
    },
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          // RTL builds: ['./src/css/custom.css', './src/css/custom-rtl.css']
          // LTR builds: ['./src/css/custom.css']
          customCss: ['./src/css/custom.css'],
        },
      } satisfies Preset.Options,
    ],
  ],

  // Mermaid flow diagrams: figma-to-doc / site-to-doc emit ```mermaid``` fences
  // for user-flow charts. Requires the `@docusaurus/theme-mermaid` dependency
  // (installed by /lore:add-docusaurus). Without it the fence renders as a plain
  // code block — harmless, but the diagram won't draw.
  markdown: { mermaid: true },
  themes: ['@docusaurus/theme-mermaid'],

  themeConfig: {
    navbar: {
      title: '{{SITE_TITLE}}',
      items: [],
    },
    footer: {
      style: 'dark',
      links: [],
      // copyright renders as raw HTML. {{LORE_ATTRIBUTION}} is a localized anchor
      // to lorekit.net ("ساخته شده با Lore" / "Built with Lore") filled by the wizard.
      copyright: '{{COPYRIGHT}} · {{LORE_ATTRIBUTION}}',
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
